version: '3.8'

services:
  rekor:
    container_name: sigstore-rekor
    build:
      context: ./rekor
      dockerfile: Dockerfile
    ports:
    - "3000:3000" 
    networks:
      - sigstore-network
    restart: unless-stopped

  dex:
    container_name: sigstore-dex
    build:
      context: ./dex
      dockerfile: Dockerfile
    env_file:
      - ./dex/.env
    ports:
    - "6001:6000" 
    networks:
      - sigstore-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6000/.well-known/openid-configuration"]
      interval: 30s
      timeout: 10s
      retries: 3

  ctlog:
    container_name: sigstore-ctlog
    build:
      context: ./ctlog
      dockerfile: Dockerfile
    volumes:
      - fulcio-data:/shared-fulcio-config
      - ctlog-data:/shared-ctlog-config
    ports:
      - "6105:6105" 
    networks:
      - sigstore-network
    restart: unless-stopped

  fulcio:
    container_name: sigstore-fulcio
    build:
      context: ./fulcio
      dockerfile: Dockerfile
    volumes:
      - fulcio-data:/shared-fulcio-config
    ports:
      - "5000:5000" 
    networks:
      - sigstore-network
    restart: unless-stopped
    depends_on:
      dex:
        condition: service_healthy


volumes:
  fulcio-data:
    name: fulcio-data
  ctlog-data:
    name: ctlog-data

networks:
  sigstore-network:
    driver: bridge
    name: sigstore-network